# Form implementation generated from reading ui file 'filename_input.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(351, 97)
        self.file_name_input = QtWidgets.QLineEdit(parent=Form)
        self.file_name_input.setGeometry(QtCore.QRect(20, 40, 311, 20))
        self.file_name_input.setObjectName("file_name_input")
        self.file_name_label = QtWidgets.QLabel(parent=Form)
        self.file_name_label.setGeometry(QtCore.QRect(20, 10, 161, 16))
        self.file_name_label.setObjectName("file_name_label")
        self.file_name_btn = QtWidgets.QPushButton(parent=Form)
        self.file_name_btn.setGeometry(QtCore.QRect(140, 70, 75, 23))
        self.file_name_btn.setObjectName("file_name_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_name_label.setText(_translate("Form", "Choose a name for your file:"))
        self.file_name_btn.setText(_translate("Form", "Ok"))
