# Form implementation generated from reading ui file '.\pdf_spliter_proj.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 278)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.execute_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.execute_btn.setGeometry(QtCore.QRect(470, 190, 111, 23))
        self.execute_btn.setObjectName("execute_btn")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 101, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.split_radio_btn = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.split_radio_btn.setObjectName("split_radio_btn")
        self.verticalLayout.addWidget(self.split_radio_btn)
        self.merge_radio_btn = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.merge_radio_btn.setObjectName("merge_radio_btn")
        self.verticalLayout.addWidget(self.merge_radio_btn)
        self.open_file_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_file_btn.setGeometry(QtCore.QRect(470, 130, 111, 23))
        self.open_file_btn.setObjectName("open_file_btn")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 190, 421, 21))
        self.progressBar.setProperty("value", 27)
        self.progressBar.setObjectName("progressBar")
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(30, 140, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.destination_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.destination_btn.setGeometry(QtCore.QRect(470, 160, 111, 23))
        self.destination_btn.setObjectName("destination_btn")
        self.destination_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.destination_label.setGeometry(QtCore.QRect(20, 230, 551, 21))
        self.destination_label.setText("")
        self.destination_label.setObjectName("destination_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.execute_btn.setText(_translate("MainWindow", "Execute"))
        self.split_radio_btn.setText(_translate("MainWindow", "Split"))
        self.merge_radio_btn.setText(_translate("MainWindow", "Merge"))
        self.open_file_btn.setText(_translate("MainWindow", "Open file(s)"))
        self.label.setText(_translate("MainWindow", "TCP - PDF Splitter"))
        self.destination_btn.setText(_translate("MainWindow", "Select Destination"))
